### ISSUE TITLE
Request: Numbered lists to follow numbering like GitHub

### ISSUE THREAD

**Issue by desimaniac** [zhuochun/md-writer#215]
GitHub numbers their numbered list as just `1.`.   As in:

```
1. first line
1. second line
1. third line
```
Github will automatically number it properly. 

Same example processed by GitHub:
1. first line
1. second line
1. third line

This makes reordering things much easier, since you don't have to keep correcting the numbers.

**Comment by zhuochun** [comment]
Oops, looks like this is due to the latest release change.

You can revert to the original behaviour by add [config](https://github.com/zhuochun/md-writer/wiki/Settings):

```
lineStyles:
  ol:
    before: "1. "
    regexMatchBefore: "(?:\\d+[\\.\\)]|[a-zA-Z]+[\\.\\)])\\s"
    regexBefore: "(?:-|\\*|\\+|\\.|\\d+[\\.\\)]|[a-zA-Z]+[\\.\\)])\\s"
```
