### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tags' of null 

### ISSUE THREAD

**Issue by timnew** [zhuochun/md-writer#3]
I got similar errors when update both tags and categories

Here is the front matter in my blog

``` yaml
layout: post
title: Page renders improperly in IE before developer tool has opened
comments: true
categories: javascript
tags:
  - javascript
  - IE
  - developer tool
  - pitfall
  - console
  - undefined
  - polyfill
date: 2014-08-01 08:00:00

---
```

Page: http://timnew.github.io/blog/2014/08/01/page-renders-improperly-in-ie-before-developer-tool-has-opened/
